name: agora
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # Custom dependencies
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter


# Specific to Flutter.
flutter:

  uses-material-design: true
  
  assets:
    - assets/images/background.png

  fonts:
    - family:  Brankic1979
      fonts:
       - asset: assets/fonts/Brankic1979-tags.ttf
